project:
  type: website

website:
  title: "Bren Digital Gallery"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: main.scss
    toc: false
    page-layout: full

editor: visual

