project:
  type: website

website:
  title: "Bren Digital Gallery"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: 
      - test.scss
      - cosmo
    css: main.scss
    toc: false
    page-layout: full

editor: visual

